### ISSUE TITLE
Update read functions to re-create resources which deleted manually

### ISSUE THREAD

**Issue by ffahri** [opsgenie/terraform-provider-opsgenie#101]

**Comment by ffahri** [comment]
#51

**Comment by matipan** [comment]
Hey @ffahri! We are going to be working on this with @marcosnils and we hope to send a PR soon enough! Any extra details we should be aware of?

**Comment by matipan** [comment]
@ffahri we have been checking other implementations to see how other providers go about handling this issues. With AWS for example, we created an s3 bucket with terraform, deleted in the console, executed `terraform plan` and it tried to re-create the bucket instead of clearing the state. 

Do you think that we should implement it like that? Meaning that it should try to re-create the resource instead of clearing the state?

**Comment by ffahri** [comment]
That's exactly what I thought at first @matipan. Since this definition is still in plans should Terraform create if not found? 
Because if it does clear the state, next terraform apply run still try to create this function.
```
 terraform state rm 'opsgenie_api_integration.cloudwatch'
```

This command will remove this definition of the state. 

Imho if the user deletes some resources manually on UI, the user also needs to fix its own plan. But like you mentioned in other providers try to re-create situations like this. 

> Current behaviour is Terraform will crash with 404.

**Comment by marcosnils** [comment]
@ffahri correct. Can we update this issue title to "Upread read functions to recreate the resource if it has been deleted" so this provider is consistent with the other ones?

**Comment by ffahri** [comment]
@matipan @marcosnils I agree checked other providers and this behavior is expected when manually deletion of resource.

**Comment by marcosnils** [comment]
Awesome @ffahri. We'll send a PR this week to fix this :muscle: . Can you assign it to us?
