### ISSUE TITLE
Broken resource opsgenie_user?

### ISSUE THREAD

**Issue by arnisoph** [opsgenie/terraform-provider-opsgenie#155]
I'm about implementing #65 and experience a super annoying behaviour of some atlassian systems messing up with the fullName field of OpsGenie users. I was able to let the OpsGenie support create an internal ticket OGS-1629 but I think this issue could be more severe/serios.

The opsgenie user resource fails to change fullName field at all:

```
  # opsgenie_user.user1 will be updated in-place
  ~ resource "opsgenie_user" "user1" {
      ~ full_name = "asdasdasd" -> "Jane Doe"
        id        = "c90ba476-c5a3-4d68-b89d-674d2a901add"
        locale    = "en_US"
        role      = "User"
        timezone  = "America/New_York"
        username  = "mail+asdasd@EXAMPLE.COM"
    }
```

Every tf plan/apply will retry this ^. asdasdasd is set via atlassian IDM/SSO while Jane Doe is part of TF config.

I am using a self-built master version. Could somebody please verify whether master is stable?

**Comment by arnisoph** [comment]
The api docs don't even mention that some magic background systems are doing things on the fullName field.

**Comment by ffahri** [comment]
Yes, new customers cannot set their full_name using the Opsgenie API , or customers who switched to Atlassian Cloud. 
Therefore in near future we need to depreciate full_name field. However we cannot get any field from api for is this customer using AtlassianCloud

**Comment by ffahri** [comment]
I'll add this to documentations to both api and terraform. We have to keep support because there are users which can use this field.

**Comment by arnisoph** [comment]
yep 👌  super strange that API docs weren't up2date 😄

**Comment by ffahri** [comment]
closing this issue, will follow internal ticket to add documentation in api docs

**Comment by zonArt** [comment]
Sorry I think I've missed the documentation update part but how should we manage full_name attribute? It looks like it's now managed by the atlassian id and it's not anymore possible to override it so what's the point with that?

**Comment by arnisoph** [comment]
@zonArt the point with what? The issue was already closed at the time of your comment.

**Comment by zonArt** [comment]
> @zonArt the point with what? The issue was already closed at the time of your comment.

The point with setting full_name attribute, if it can't be modified, why even bother with it? It's still mandatory but it's just useless since it can't modify its value leading in an endless loop on which you apply terraform and it says it will modify something but it can't so next time is the same and whenever you do a plan you cannot tell that your infra is clean since you still have these modification ongoing

**Comment by arnisoph** [comment]
So your suggestion is to drop the attribute in the terraform resource?

**Comment by zonArt** [comment]
I'm not sure what's the best way of dealing with this param because at user creation it's still needed I guess but once the account is linked with atlassian there is no way to modify it from what was initially put before linking accounts (not sure if I'm clear enough). So if it is possible to remove it (or at least making it optional) would be great. I don't know what happen when you create a user in opsgenie without specifying a full name, will it come automatically from the atlassian linked email ?
