### ISSUE TITLE
Define SendAfter for immediately has to be specified as zero

### ISSUE THREAD

**Issue by pussinboots** [opsgenie/terraform-provider-opsgenie#244]
The current implementation make the field send_after mandatory otherwise the Opsgenie API
raise the error SendAfter cannot be empty.

And there is no way to define 0 (mean immediately) because of the if statement in the code line below.

https://github.com/opsgenie/terraform-provider-opsgenie/blob/5f0f42e2594529837136630122399f499105ba40/opsgenie/resource_opsgenie_notification_rule.go#L443

**Comment by tzaleski-vertexinc** [comment]
We're affected by this as well. 
One way around this is to set it to e.g. 1 to create the NotificationRule and then change to 0 which works (at least in Pulumi that uses this provider).
But it would be nice if we could set it to 0 right away.

**Comment by corstuur** [comment]
We are also running into this issue.
You can't directly set it to 0. This is really a bad check for user creation.
This really needs to be fixed. Like @tzaleski-vertexinc you can set it first to 1 then change in the web interface to 0. After that you can change your terraform code and change the send after to 0 so that it will not change back to 1.

**Comment by corstuur** [comment]
I created a PR request that should fix this.
#350

**Comment by arjunrajpal** [comment]
We have merged the fix and it is available in [v0.6.26](https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.26).
