### ISSUE TITLE
api_key refuses to output

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [opsgenie/terraform-provider-opsgenie#269]
### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.62.0
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.5

### Affected Resource(s)
 - opsgenie_api_integration.datasync.api_key
 

### Terraform Configuration Files
```hcl
resource "opsgenie_api_integration" "datasync" {
  name          = "datasync monitor"
  type          = "API"
  owner_team_id = opsgenie_team.swe.id

  responders {
    type = "team"
    id   = opsgenie_team.swe.id
  }
}
output "datasync_api_key" {
  value = opsgenie_api_integration.datasync.api_key
}

```

### Debug Output
https://gist.github.com/krestivo-kdinfotech/022a02c27067b84f87e77b2b5cd2648f

### Expected Behavior
I should see the api_key in the output

### Actual Behavior
There is no output at all

### Steps to Reproduce
1. `terraform apply`
2. Look at the output
3. There isn't any. WTF?

### Important Factoids
If I output opsgenie_api_integration.datasync.id , that works. But not the api_key, which is what I really need to have in the remote state, not the ID, which is useless.

**Comment by nomaster** [comment]
This happened to us after importing the resource into the Terraform state. When creating the resource as new, the attribute 'api_key' appeared in the output.

**Comment by nissessenap** [comment]
Has anyone created an issue about this to the opsgenie support? 
Seems rather silly that nothing has happened for 7 months.

Either the integration API needs to be updated or they need to make some other API public so we can get the api_key. When that is done it shouldn't be a big task to update the provider.

**Comment by singhujjwal** [comment]
> This happened to us after importing the resource into the Terraform state. When creating the resource as new, the attribute 'api_key' appeared in the output.


This is really blocking people who want to migrate from older terraform version, any planning on this issue?
A simple terraform import import the `api_key` value as null which makes the subsequent `terraform apply` to fail.

**Comment by singhujjwal** [comment]
> This happened to us after importing the resource into the Terraform state. When creating the resource as new, the attribute 'api_key' appeared in the output.

@nomaster Did you get any workaround this problem ?

**Comment by nomaster** [comment]
> @nomaster Did you get any workaround this problem ?

Yes, but only by not using the import functionality. It was okay for us to delete resource by hand and create it as new.

**Comment by baprx** [comment]
I opened a support ticket and Atlassian created an issue to track this bug, you can vote here to increase the visibility: https://jira.atlassian.com/browse/OPSGENIE-1345

**Comment by arjunrajpal** [comment]
Hi everyone, the way `terraform import opsgenie_api_integration.<resource_name> <integration-id>` works is that under the hood, it makes a call to https://docs.opsgenie.com/docs/integration-api#get-integration which returns information related to that integration. However since the public api does not return api_key, we also cannot populate api_key in terraform state file while importing hence the output of api_key comes out to be null. While these APIs were being written, the apiKey was added into only create endpoint especially because read/write access are taken in this endpoint. There are no plans to modify existing api or create a new endpoint to specifically return api_key.

At present, we can only fetch the api key as output at the time of creation of the integration.

**Comment by nissessenap** [comment]
Great to see that someone from opsginie finally looks at this.
Can't say I'm surprised by your decision to not be willing to do any API changes. Since that is the case i suggest that you remove the import statement since it doesn't do anything and never will. That way your users will at least not waste time trying to do it.

**Comment by arjunrajpal** [comment]
> Great to see that someone from opsginie finally looks at this. Can't say I'm surprised by your decision to not be willing to do any API changes. Since that is the case i suggest that you remove the import statement since it doesn't do anything and never will. That way your users will at least not waste time trying to do it.

@NissesSenap Unfortunately, returning the api_key from the API brings security concerns. However, the import functionality is still working because its objective is to maintain the state of an Opsgenie resource through Terraform.

**Comment by arjunrajpal** [comment]
We are closing the ticket since it's not possible to return api_key during import by changing the provider.

**Comment by nissessenap** [comment]
@arjunrajpal you are showing it in the UI though, but I do agree with you, it is a security concern to return it after creation. But if that is your stance then please **remove** it from the UI as well, be consistent be API first.
